### ISSUE TITLE
브라우저에서 로그인시 로그인 처리가 안되는 문제

### ISSUE THREAD

**Issue by wkddngus5** [NHNNEXT/2017-REAL-MAC-HACK-KI#124]
- postman에서 보내면 잘 되는 로그인이 브라우저에서는 안 되는 것 같습니다

**Comment by bbq923** [comment]
fetch를 사용해 로그인 시 `credentials: 'same-origin'` 옵션을 주어 해결했습니다.
쿠키 문제였네요.
