### ISSUE TITLE
Api "/user/login" 가 userId 를 제공하는 방법

### ISSUE THREAD

**Issue by wlals822** [NHNNEXT/2017-REAL-MAC-HACK-KI#70]
회원가입을 한 상태의 사람이 이메일과 비밀번호로 로그인을 하게 되면
user Id 를 "/user" 로 가져오는 방법밖에는 없는듯 합니다. 

로그인 api 에서 id도 전송하는 것이 좋아보입니다.

**Comment by bbq923** [comment]
`/users/{id}` 로 요청시 해당 id를 가지는 User 객체를 리턴합니다.
