### ISSUE TITLE
WEB-INF 설정

### ISSUE THREAD

**Issue by wkddngus5** [NHNNEXT/2017-REAL-MAC-HACK-KI#78]
실제 서비스 하고 있는 프로젝트는 클라이언트 브라우저에서 임의로 html(jsp, handlebars 등등)에 접근하는 것을 막기 위해 WEB-INF에서 관리한다고 합니다. 저희도 그렇게 해볼까요?
- http://blog.naver.com/PostView.nhn?blogId=p952973&logNo=220952966055&parentCategoryNo=&categoryNo=16&viewDate=&isShowPopularPosts=true&from=search
- http://egloos.zum.com/kwon37xi/v/2850553

**Comment by bbq923** [comment]
그럼 swagger 같은 경우엔 어떻게 접근 해야 하나요? 지금 `/swagger-ui.html`  이렇게 접근하고 있는데 이것도 막히는 건가요?

**Comment by wkddngus5** [comment]
오... 스웨거는 생각도 안해봤는데 ㅎㅎ 일단 스웨거만 기존에 있던 경로에 그냥 놔두는 방법이랑 아니면 스웨거-ui파일도 컨트롤러를 거치는 방법 두 가지가 생각나네요?
