### ISSUE TITLE
회원 가입시 이메일 중복 체크

### ISSUE THREAD

**Issue by Yongjai** [NHNNEXT/2017-REAL-MAC-HACK-KI#88]
회원가입을 할 때, 이메일 중복을 따로 체크하지 않고 회원가입을 하는 버튼을 누르는 동시에 중복확인과 회원가입 절차를 진행하는데 이를 분리할 필요성이 있어 보입니다.

보통 회원가입을 할 때, 이메일(id) 중복 체크를 한 뒤에 나머지 정보를 입력하는게 일반적이고 사용자 입장에서도 그게 편하다고 생각합니다.

**Comment by wlals822** [comment]
가입된 이메일인지 확인해서 true, false 를 반환해주는 api가 있으면 되겠네요.
request   {"email":"string"}
response  {"isSignUp": true} 
이정도? 
클라에서는 이메일 입력창에서 커서가 옮겨지면 바로 콜해서 확인하고 표시하면 좋겠네요.

**Comment by Yongjai** [comment]
That's exactly what I want !

**Comment by bbq923** [comment]
implemented.
`GET /users/`
request body : 
{ "email":"your@email.com" }
return :
{ true(false) }
